<!DOCTYPE html>
<html>
<head>
    <title>BUYSELL</title>
</head>
<body>
<h1>Shop</h1><hr>
<a href = "/">дом</a>
<h4>Авторизация</h4>
<form action="/login" method="post">
    Эл. почта: <input type="text" name="username"><br><br>
    Пароль: <input type="password" name="password"><br><br>

    <input type="submit" value="Вход"/>
</form>
<a href="/registration">Зарегистрироваться</a>
</body>
</html>